            //FINAL
    /*
     1.DALAM VARIABLE 
     JIKA SEBUAH VARIABLE MENGGUNAKAN KATA FINAL MAKA VARIABLE TERSEBUT AKAN BERUBAH MENJADI KONSTAN TIDAK DAPAT DIRUBAH
     2.DALAM METHOD
     JIKA SEBUAH METHODE MENGGUNAKAN AKSES FINAL MAKA METHOD TERSEBUT TIDAK BISA DI OVERRIDE METHOD NYA OLEH CLASS ANAKNYA/SUB KELAS
     */
